
backend:
   database:  org.efaps.db.databases.PostgreSQLDatabase
   transactionManager: com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionManagerImple
   datasource:
      url: jdbc:postgresql://127.0.0.1:5432/lite
      user: efaps
      password: efaps

sever:
   url: http://localhost:8080
