
backend:
   database:  org.efaps.db.databases.PostgreSQLDatabase
   transaction:
      manager: com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionManagerImple
      timeout: 600
   datasource:
      url: jdbc:postgresql://127.0.0.1:5432/lite
      user: efaps
      password: efaps

sever:
   url: http://localhost:8080

keycloak:
   configFile: keycloak.json
